name: wrf_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - attrs=25.3.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.24.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfgrib=0.9.15.0
  - cftime=1.6.4
  - charset-normalizer=3.4.1
  - click=8.1.8
  - contourpy=1.2.1
  - cycler=0.12.1
  - eccodes=2.39.0
  - findlibs=0.0.5
  - fonttools=4.56.0
  - freetype=2.13.3
  - geos=3.13.1
  - gtest=1.16.0
  - h2=4.2.0
  - h5py=3.12.1
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jasper=4.2.5
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=20.1.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.1
  - lz4-c=1.10.0
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.2
  - openjpeg=2.5.3
  - openssl=3.4.1
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=25.0.1
  - proj=9.6.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygrib=2.1.6
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-eccodes=2.37.0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=59.8.0
  - shapely=2.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.49.1
  - statsmodels=0.14.4
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xarray=2023.12.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - basemap==1.4.1
      - basemap-data==1.3.2
      - numpy==1.26.4
      - packaging==23.2
      - pyproj==3.6.1
      - pyshp==2.3.1
      - wrapt==1.17.2
      - wrf-python==1.3.4.1
